// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX21oFNlP1b0zAxvaQdHhE_MxaVRB_9EI',
    appId: '1:804412839202:web:70b7c32e4cf54ed46a017b',
    messagingSenderId: '804412839202',
    projectId: 'code-fire-81d35',
    authDomain: 'code-fire-81d35.firebaseapp.com',
    storageBucket: 'code-fire-81d35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVJeRncDWUWwLX6w6FMBpP2WkQRXqMSKs',
    appId: '1:804412839202:android:bd4b7b1e9eb9ba846a017b',
    messagingSenderId: '804412839202',
    projectId: 'code-fire-81d35',
    storageBucket: 'code-fire-81d35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq7PbcKYHtuyPIPYNBLIOKsnRj4KNajW0',
    appId: '1:804412839202:ios:0430c1d5d8956fc46a017b',
    messagingSenderId: '804412839202',
    projectId: 'code-fire-81d35',
    storageBucket: 'code-fire-81d35.appspot.com',
    iosClientId: '804412839202-5461ta18fu98fp4h49jgmbpvj6gpeovd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq7PbcKYHtuyPIPYNBLIOKsnRj4KNajW0',
    appId: '1:804412839202:ios:0430c1d5d8956fc46a017b',
    messagingSenderId: '804412839202',
    projectId: 'code-fire-81d35',
    storageBucket: 'code-fire-81d35.appspot.com',
    iosClientId: '804412839202-5461ta18fu98fp4h49jgmbpvj6gpeovd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
